### ISSUE TITLE
IS it up to date

### ISSUE THREAD

**Issue by minecraft-fff** [SlimefunGuguProject/Supreme#28]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Supreme/issues)，且没有找到相同的问题

### 问题描述

开机出现
[11:17:44 INFO]: [Supreme] Enabling Supreme vBuild 15 zh-CN(SlimefunGuguProject) (git 50ee209)
[11:17:44 INFO]: [Supreme] ########################################
[11:17:44 INFO]: [Supreme]       Supreme 2.0  作者:RelativoBR       
[11:17:44 INFO]: [Supreme]          汉化:SlimefunGuguProject        
[11:17:44 INFO]: [Supreme] ########################################
[11:17:44 INFO]: [Supreme] 自动更新: 已启用
[11:17:44 INFO]: [Supreme] 已加载语言: zh-CN
[11:17:44 INFO]: [Supreme] 至尊研究院1.0物品ID兼容: 已禁用
[11:17:44 ERROR]: Error occurred while enabling Supreme vBuild 15 zh-CN(SlimefunGuguProject) (git 50ee209) (Is it up to date?)
java.lang.InstantiationError: org.bukkit.enchantments.EnchantmentWrapper
        at com.github.relativobr.supreme.util.EnchantsAndEffectsUtil.getEnchants(EnchantsAndEffectsUtil.java:123) ~[Supreme-Build 15 zh-CN(SlimefunGuguProject) (git 50ee209).jar:?]
        at com.github.relativobr.supreme.util.EnchantsAndEffectsUtil.addGearBasicEnchants(EnchantsAndEffectsUtil.java:104) ~[Supreme-Build 15 zh-CN(SlimefunGuguProject) (git 50ee209).jar:?]
        at com.github.relativobr.supreme.gear.AbstractWeapons.setup(AbstractWeapons.java:26) ~[Supreme-Build 15 zh-CN(SlimefunGuguProject) (git 50ee209).jar:?]
        at com.github.relativobr.supreme.setup.MainSetup.setup(MainSetup.java:26) ~[Supreme-Build 15 zh-CN(SlimefunGuguProject) (git 50ee209).jar:?]
        at com.github.relativobr.supreme.Supreme.onEnable(Supreme.java:181) ~[Supreme-Build 15 zh-CN(SlimefunGuguProject) (git 50ee209).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:642) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:553) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1130) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[leaves-1.20.4.jar:git-Leaves-"11c94f7"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:17:44 INFO]: [Supreme] Disabling Supreme vBuild 15 zh-CN(SlimefunGuguProject) (git 50ee209)          

leaves核心

### 复现步骤

1.开机

### 预期行为

正常加载

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

veabaa21-Beta

### 插件版本

15

**Comment by ybw0014** [comment]
32c404f9ce79d8aeef7a4c00e251cdf4132e5e29
